questions = {}

class Questions_Seed:
    def __init__(self, question, answer, category):
        self.question = question
        self.answer = answer
        self.category = category

    def __str__(self):
        return f'{self.question}, {self.answer}, {self.category}'
    

    


# Some answers maybe generated by the structure itself? Igore those for now
    

